import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { ClientsProvider } from "@/context/ClientsContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Ajuste os pesos conforme necessário
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Ajuste os pesos conforme necessário
});

export const metadata: Metadata = {
  title: "Laytime Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="f-hull bg-white">
      <body className={`h-full bg-white ${poppins.className} ${inter.className}`}>
        <ClientsProvider>
          {children}
        </ClientsProvider>
      </body>
    </html>
  );
}
